package com.crawler.source.dao;

import com.crawler.source.domain.Source;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    Source selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Source record);
    
    Source selectByChannelMaxNum(String channel);
}