package com.crawler.source.domain;

import java.util.Date;

public class App {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.info_url
     *
     * @mbggenerated
     */
    private String infoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.down_url
     *
     * @mbggenerated
     */
    private String downUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.down_num
     *
     * @mbggenerated
     */
    private String downNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.id
     *
     * @return the value of app.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.id
     *
     * @param id the value for app.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.name
     *
     * @return the value of app.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.name
     *
     * @param name the value for app.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.size
     *
     * @return the value of app.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.size
     *
     * @param size the value for app.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.version
     *
     * @return the value of app.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.version
     *
     * @param version the value for app.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.info_url
     *
     * @return the value of app.info_url
     *
     * @mbggenerated
     */
    public String getInfoUrl() {
        return infoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.info_url
     *
     * @param infoUrl the value for app.info_url
     *
     * @mbggenerated
     */
    public void setInfoUrl(String infoUrl) {
        this.infoUrl = infoUrl == null ? null : infoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.down_url
     *
     * @return the value of app.down_url
     *
     * @mbggenerated
     */
    public String getDownUrl() {
        return downUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.down_url
     *
     * @param downUrl the value for app.down_url
     *
     * @mbggenerated
     */
    public void setDownUrl(String downUrl) {
        this.downUrl = downUrl == null ? null : downUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.down_num
     *
     * @return the value of app.down_num
     *
     * @mbggenerated
     */
    public String getDownNum() {
        return downNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.down_num
     *
     * @param downNum the value for app.down_num
     *
     * @mbggenerated
     */
    public void setDownNum(String downNum) {
        this.downNum = downNum == null ? null : downNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.update_time
     *
     * @return the value of app.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.update_time
     *
     * @param updateTime the value for app.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}